#!/bin/bash

# Build everything that needs building
make -j

fib=1134903170
echo Fibonacci 45 is $fib

# Run every object and script
for file in *.{o,sh}; do

	if [[ $(time ./$file) == $fib ]]; then
		echo -e $file\\tpass
	else
		echo -e $file\\tfail
	fi
done
