#!/bin/bash

# Build everything that needs building
make -j

fib=832040

# Run every object and script
for file in *.{o,sh,hs,js}; do

	# Prepend the correct interpreter if necessary
	interpreter=''
	[[ $file =~ hs ]] && interpreter=runhaskell
	[[ $file =~ js ]] && interpreter=node

	# Run each script/object
	if [[ $(time $interpreter ./$file) == $fib ]]; then
		echo -e $file\\tpass
	else
		echo -e $file\\tfail
	fi
done
